version: '2'
services:
  jenkins-dockercap:
    image: jenkins-dockercap
    # restart_policy: unless-stopped
    ports:
     - "8080:8080"
     - "50000:50000"
    environment:
     JAVA_OPTS: -Dhudson.footerURL=http://www.site.test
     JAVA_OPTS: -Djava.awt.headless=true
     JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    # stdin_open: true
    # volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
